/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutTicketDao
 */
export interface PutTicketDao {
    /**
     * 
     * @type {string}
     * @memberof PutTicketDao
     */
    fio?: string;
    /**
     * 
     * @type {string}
     * @memberof PutTicketDao
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof PutTicketDao
     */
    message?: string;
}

export function PutTicketDaoFromJSON(json: any): PutTicketDao {
    return PutTicketDaoFromJSONTyped(json, false);
}

export function PutTicketDaoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutTicketDao {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fio': !exists(json, 'fio') ? undefined : json['fio'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function PutTicketDaoToJSON(value?: PutTicketDao | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fio': value.fio,
        'phone': value.phone,
        'message': value.message,
    };
}


