/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TicketDao,
    TicketDaoFromJSON,
    TicketDaoFromJSONTyped,
    TicketDaoToJSON,
} from './';

/**
 * 
 * @export
 * @interface TicketListDao
 */
export interface TicketListDao {
    /**
     * 
     * @type {number}
     * @memberof TicketListDao
     */
    totalPages?: number;
    /**
     * 
     * @type {Array<TicketDao>}
     * @memberof TicketListDao
     */
    list?: Array<TicketDao>;
}

export function TicketListDaoFromJSON(json: any): TicketListDao {
    return TicketListDaoFromJSONTyped(json, false);
}

export function TicketListDaoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketListDao {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'list': !exists(json, 'list') ? undefined : ((json['list'] as Array<any>).map(TicketDaoFromJSON)),
    };
}

export function TicketListDaoToJSON(value?: TicketListDao | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalPages': value.totalPages,
        'list': value.list === undefined ? undefined : ((value.list as Array<any>).map(TicketDaoToJSON)),
    };
}


