spring:
  datasource:
    url: jdbc:postgresql://172.17.0.4/postgres
    username: postgres
    password: passwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
